services:
  scribd-downloader:
    image: ghcr.io/phambinh0905bg/scribd-downloader:latest
    container_name: scribd-downloader
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - CLEANUP_MINUTES=300
      - MAX_CONCURRENT_DOWNLOADS=4
      - DEVICE_SCALE_FACTOR=2.0
    volumes:
      - /disk1/data/downloads:/app/downloads
    shm_size: 2gb
    networks:
      - home-network

networks:
  home-network:
    external: true
